name: Deploy Tagshop to GitHub Pages

# Trigger the workflow manually or on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up GitHub Pages deployment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TAGSHOP_TOKEN }}   # Use your secret here
          publish_dir: ./                              # deploy everything in repo root
          force_orphan: true                           # overwrite gh-pages branch

      # 3. Optional: Confirm deployment
      - name: Deployment completed
        run: echo "Tagshop site deployed to GitHub Pages!"
