name: Deploy Tagshop to GitHub Pages

# Trigger on push to main or manual trigger
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TAGSHOP_TOKEN }}   # <-- must match secret name
          publish_dir: ./                              # deploy root folder
          force_orphan: true                           # overwrite gh-pages branch

      # 3. Confirmation
      - name: Deployment completed
        run: echo "✅ Tagshop site deployed to GitHub Pages!"
